title: Sukriti Shah # your name (or website title) here
logo: "images/logo.png" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Enthusiast with 4+ years of experience as a Subject Matter Expert in Mathematics in Ed-tech domain 
  <br><br>
  <a href="https://www.linkedin.com/in/sukritishah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
